add Counter app
mindera-school/MS5-FE-Vanilla-Exercicies pull request #12
Opened 2023-03-21 09:47 UTC by gabiprosfriends

2023-03-21 09:51 UTC, LeoHabs requested changes

2023-03-21 09:51 UTC, LeoHabs commented on CounterApp/index.html
> +        </script>
Mete isto num ficheiro à parte de js e importa

2023-03-21 09:51 UTC, LeoHabs commented on CounterApp/script.js
> +console.log("smart")
Remove console logs quando acabares de desenvolver as cenas

2023-03-21 09:55 UTC, Rocha1313 commented on CounterApp/index.html
> +        </script>
Porque este script esta aqui e tens um ficheiro `js` com nada basicamente

2023-03-21 09:56 UTC, Adan0k requested changes

2023-03-21 09:56 UTC, Adan0k commented on CounterApp/index.html
> +        </script>
põe toda a lógica no ficheiro `js`, não é bom ter isso no `index`

2023-03-21 09:56 UTC, Adan0k commented on CounterApp/script.js
> +console.log("smart")
esse ficheiro não está linkado ao teu `html` portanto isso não vai ser `executado`

2023-03-21 09:56 UTC, Adan0k commented on CounterApp/style.css
> +}
isso não devia ser no `body`?

```suggestion
body{
    height: 100%;
    width: 100%;
    background-color: brown;
}
```

2023-03-21 10:00 UTC, Adan0k commented on CounterApp/style.css
> +    align-items: flex-start;
porquê tu tá fazendo `align-items` no botão? se tu quer alinhar o texto usa `text-align`

2023-03-21 10:24 UTC, 201flaviosilva commented on CounterApp/style.css
> +    align-items: flex-start;
Na verdade, eu acho que está aqui uma grande confusão, porque `align-items` não funciona sem o `flex`

2023-03-21 10:32 UTC, Adan0k commented on CounterApp/style.css
> +
apaga um desses espaços em branco

2023-03-21 12:11 UTC, Adan0k requested changes

2023-03-21 12:11 UTC, Adan0k commented on CounterApp/script.js
> +            span.textContent= value;
o `=` ta colado na propriedade
```suggestion
            span.textContent = value;
```

2023-03-21 12:11 UTC, Adan0k commented on CounterApp/script.js
> +            span.textContent= value;
o mesmo aqui
```suggestion
            span.textContent = value;
```

2023-03-21 12:11 UTC, Adan0k commented on CounterApp/script.js
> +        let value= 0;
bora dar um espaçamento nessas atribuições?
```suggestion
        const buttonMinus = document.getElementById("minus-button")
        const buttonPlus = document.getElementById("plus-button")
        const span = document.getElementById("value")
        
        let value = 0;
```

2023-03-21 12:14 UTC, Rocha1313 commented on CounterApp/script.js
> +        buttonMinus.addEventListener("click", ()=>{
```suggestion
        buttonMinus.addEventListener("click", () => {
```

2023-03-21 12:14 UTC, Rocha1313 commented on CounterApp/script.js
> +        buttonPlus.addEventListener("click", ()=>{
```suggestion
        buttonPlus.addEventListener("click", () => {
```

2023-03-21 12:14 UTC, Rocha1313 commented on CounterApp/index.html
> +<html lang="pt-br">
pt-br? estranho

2023-03-21 12:15 UTC, LeoHabs requested changes
Isto para além das questões de formatação que o Adan ( com N) já comentou

2023-03-21 12:15 UTC, LeoHabs commented on CounterApp/script.js
> +        const span= document.getElementById("value")
Uma constante com um nome de uma tag é uma prática péssima, imagina que tens mais cenas que são spans, fazes o q? Arranja um nome mais descritivo tipo countDisplay, sei lá hahaha

2023-03-21 12:25 UTC, LeoHabs approved these changes

2023-03-21 12:25 UTC, LeoHabs commented on CounterApp/index.html
> +<html lang="pt-br">
Wtf realmente

2023-03-21 12:25 UTC, Adan0k commented on CounterApp/script.js
> +            countDisplay.textContent= value;
```suggestion
            countDisplay.textContent = value;
```

2023-03-21 12:26 UTC, Adan0k commented on CounterApp/script.js
> +            countDisplay.textContent= value;
```suggestion
            countDisplay.textContent = value;
```

2023-03-21 12:28 UTC, Adan0k commented on CounterApp/index.html
> +<html lang="pt-br">
pt-br😎

2023-03-21 15:02 UTC, LeoHabs approved these changes

2023-03-22 10:01 UTC, Adan0k approved these changes

2023-03-22 10:19 UTC, merged