Add: TicTacToe
mindera-school/MS5-FE-Vanilla-Exercicies pull request #2
Opened 2023-02-22 11:08 UTC by Gabriel-Sous-a

2023-02-23 12:17 UTC, LeoHabs commented on TicTacToe/first.js
> +let score1 = 0;
```suggestion
let playerOne = 0;
```
Deves ter variaveis mais especificas

2023-02-23 12:19 UTC, LeoHabs commented on TicTacToe/first.js
> +let draw = 0;
E neste caso eu poria drawnGames ou assim

2023-02-23 12:23 UTC, LeoHabs commented on TicTacToe/first.js
> +const play = document.getElementById("play");
```suggestion
const playBtn = document.getElementById("play");
```
Acho que faz sentido dizer o tipo de elemento q é. Neste caso o botão de dar play

2023-02-23 12:24 UTC, LeoHabs commented on TicTacToe/first.js
> +    console.log(count);
Eliminar os logs

2023-02-23 12:24 UTC, LeoHabs commented on TicTacToe/first.js
> +let count = 1;
Também podes ser mais especifico no que estás a contar aqui

2023-02-23 12:25 UTC, LeoHabs commented on TicTacToe/first.js
> +    console.log("horizontal");
Same as above

2023-02-23 12:37 UTC, LeoHabs commented on TicTacToe/first.js
> +    document.getElementById("draw").innerHTML = draw + 1;
Poderias ter dado um id melhor

2023-02-23 12:39 UTC, LeoHabs commented on TicTacToe/index.css
> +  font-size: 500%;
Sangrei dos olhos

2023-02-23 12:39 UTC, LeoHabs commented on TicTacToe/index.css
> +  padding-top: 12vh;
Deves usar unidades absolutas

2023-02-23 12:40 UTC, LeoHabs commented on TicTacToe/index.css
> +  padding-top: 2vh;
Same as above

2023-02-23 12:41 UTC, LeoHabs commented on TicTacToe/index.html
> +          <button id="topleft" class="top container text restart"> </button>
Isto pronto é aquele doideira que falamos na aula ahahah

2023-02-23 12:42 UTC, LeoHabs commented on TicTacToe/index.html
> +    <script src="first.js"></script>
O nome do ficheiro msm à Gabi hahaha

2023-02-23 16:15 UTC, Gabriel-Sous-a commented on TicTacToe/index.html
> +    <script src="first.js"></script>
5 estrelas

2023-02-23 16:55 UTC, Adan0k requested changes

2023-02-23 16:55 UTC, Adan0k commented on TicTacToe/first.js
> +  if (verification() == true) {
põe os três iguais
```suggestion
  if (verification() === true) {
```

2023-02-23 16:55 UTC, Adan0k commented on TicTacToe/first.js
> +  if (verification() == "game draw") {
aqui também
```suggestion
  if (verification() === "game draw") {
```

2023-02-23 16:55 UTC, Adan0k commented on TicTacToe/first.js
> +  //check diogonal
acho que o diogo não tem algo haver com isso, mete diagonal

2023-02-23 16:55 UTC, Adan0k commented on TicTacToe/index.html
> +    <script src="first.js"></script>
muda o nome do ficheiro
```suggestion
    <script src="script.js"></script>
```

2023-02-23 16:55 UTC, Adan0k commented on TicTacToe/first.js
> +  }
Faz um operador ternario

2023-02-23 17:48 UTC, 201flaviosilva requested changes

2023-02-23 17:48 UTC, 201flaviosilva commented on TicTacToe/first.js
> +let playerTwo = 0;
Já vi nomes mais explícitos como:
```suggestion
let playerOneScore = 0;
let playerTwoScore = 0;
```

Mas pronto, serve

2023-02-23 17:48 UTC, 201flaviosilva commented on TicTacToe/first.js
> +boardArray.forEach(function (button) {
```suggestion
boardArray.forEach(button => {
```

Consistência

2023-02-23 17:48 UTC, 201flaviosilva commented on TicTacToe/first.js
> +  } else {
Porque é que só este `if` é que tem direito a `else`?

2023-02-23 17:48 UTC, 201flaviosilva commented on TicTacToe/first.js
> +    if (gameCounter === 9) {
estou confuso

2023-02-23 17:48 UTC, 201flaviosilva commented on TicTacToe/first.js
> +    boardArray.forEach(function (e) {
```suggestion
    boardArray.forEach(e => {
```

2023-02-23 17:48 UTC, 201flaviosilva commented on TicTacToe/first.js
> +    boardArray.forEach(function (e) {
```suggestion
    boardArray.forEach(e => {
```

2023-02-23 17:48 UTC, 201flaviosilva commented on TicTacToe/first.js
> +    if (getLetter(gameCounter) === "O") {
Aqui não deveria de ser um `else`, em vez de um outro `if`?

2023-02-23 17:48 UTC, 201flaviosilva commented on TicTacToe/index.css
> +  padding: 20px, 60px, 0, 60px;
Separado por virgulas?
```suggestion
  padding: 20px 60px 0 60px;
```

2023-02-23 17:48 UTC, 201flaviosilva commented on TicTacToe/index.css
> +  font-size:150px;
Formatação
```suggestion
  font-size: 150px;
```

2023-02-28 16:38 UTC, Gabriel-Sous-a commented on TicTacToe/first.js
> +  } else {
porque é o ultimo if

2023-03-02 15:59 UTC, 201flaviosilva requested changes

2023-03-02 15:59 UTC, 201flaviosilva commented on TicTacToe/index.css
> +}
`button` antes do `body`?

2023-03-02 15:59 UTC, 201flaviosilva commented on TicTacToe/index.html
> +    <script src="script.js"></script>
```suggestion
    <script src="./script.js"></script>
```

2023-03-02 15:59 UTC, 201flaviosilva commented on TicTacToe/script.js
> +  if (verification() == true) {
Estás a onde na primária?

```suggestion
  if (verification()) {
```

2023-03-02 15:59 UTC, 201flaviosilva commented on TicTacToe/script.js
> +  }
Porque é que tens várias funções dentro de outras funções?

2023-03-02 15:59 UTC, 201flaviosilva commented
Tens conflitos

2023-03-03 15:28 UTC, Gabriel-Sous-a commented on TicTacToe/script.js
> +  if (verification() == true) {
Isso o Ricardo disse que era mais facil de ler o codigo se tivesse os iguais mas pronto.. eu mudo ahaha

2023-03-07 11:13 UTC, 201flaviosilva approved these changes
Podes passar

2023-03-07 11:37 UTC, LeoHabs approved these changes

2023-03-07 13:13 UTC, Rocha1313 approved these changes

2023-03-07 13:35 UTC, Adan0k approved these changes
ao verificar novamente, vi que o que foi pedido foi alterado `good work`

2023-03-07 13:37 UTC, merged