Bg color
mindera-school/MS5-FE-Vanilla-Exercicies pull request #3
Opened 2023-02-22 11:20 UTC by Adan0k

2023-02-22 11:36 UTC, Gabriel-Sous-a requested changes
Fiz alguns comentários de coisas que tens que mudar, mas lembra te que o `ChangeBGColor/.DS_Store` devia ser posto no `.gitignore`

2023-02-22 11:36 UTC, Gabriel-Sous-a commented on ChangeBGColor/index.js
> +let button = document.querySelector("input");
Este `let` devia ser um `const`
```suggestion
const button = document.querySelector("input");
```

2023-02-22 11:36 UTC, Gabriel-Sous-a commented on ChangeBGColor/index.html
> +    <input type="color" name="" id="switch">
este `id` não esta a ser usado

2023-02-22 11:36 UTC, Gabriel-Sous-a commented on ChangeBGColor/index.html
> +    <title>Document</title>
Bom nome! Podias ter sido especifico
```suggestion
    <title>ChangeBgColor</title>
```

2023-02-22 12:02 UTC, Gabriel-Sous-a requested changes
Melhoraste mas tem atenção ao javascript e a formatação

2023-02-22 12:02 UTC, Gabriel-Sous-a commented on ChangeBGColor/.gitignore
> +# Created by https://www.toptal.com/developers/gitignore/api/macos,visualstudiocode
Poe estas alterações no `.gitignore` geral https://github.com/mindera-school/MS5-FE-Vanilla-Exercicies/blob/main/.gitignore

2023-02-22 12:02 UTC, Gabriel-Sous-a commented on ChangeBGColor/Readme.md
> + 4. wow the background color have changed!
Tenta manter consistencia 
```suggestion
 3. Choose a color 
 4. Wow the background color have changed!
```

2023-02-22 12:02 UTC, Gabriel-Sous-a commented on ChangeBGColor/index.html
> +    <link rel="stylesheet" href="style.css">
Muito bem!

2023-02-22 12:02 UTC, Gabriel-Sous-a commented on ChangeBGColor/index.js
> +document.querySelector("input").addEventListener("change", () => document.body.style.background = button.value);
O `button` não está atribuido 
```suggestion
const button = document.querySelector("input");
button.addEventListener("change", () => document.body.style.background = button.value);
```

2023-02-22 12:02 UTC, Gabriel-Sous-a commented on ChangeBGColor/style.css
> +body{
```suggestion
body {
```

2023-02-23 16:21 UTC, Rocha1313 approved these changes
Very Nice

2023-02-23 16:23 UTC, Gabriel-Sous-a approved these changes

2023-02-23 16:24 UTC, merged