Rock Paper Scissors Implementation
mindera-school/MS5-FE-Vanilla-Exercicies pull request #4
Opened 2023-02-22 11:28 UTC by Rocha1313

This is the awesome rock paper scissors code 🦁

2023-02-22 14:21 UTC, 201flaviosilva commented on PedraPapelTesoura/Readme.md
> +Thanks to **me** that make that project possible!
Temos um jovem engraçado na turma que está com vontade de ir embora

2023-02-23 16:35 UTC, Adan0k requested changes

2023-02-23 16:35 UTC, Adan0k commented on PedraPapelTesoura/rockPaperScissors.js
> +console.log();
Remove o `console.log` e muda o nome do ficheiro, põe `script.js`

2023-02-23 16:35 UTC, Adan0k commented on PedraPapelTesoura/Readme.md
> +```
```suggestion
```js
```

2023-02-23 16:35 UTC, Adan0k commented on PedraPapelTesoura/index.css
> +#exercise2 {
nice, ganda nome

2023-02-23 16:35 UTC, Adan0k commented on PedraPapelTesoura/index.css
> +#buttonStyle{
mete um nome mais descritivo

2023-02-23 16:35 UTC, Adan0k commented on PedraPapelTesoura/index.css
> +.buttonStyle {
o id e a classe tem o mesmo nome, parece meio mal

2023-02-23 16:35 UTC, Adan0k commented on PedraPapelTesoura/index.html
> +    <title>Color</title>
Põe um `tittle` que tenha haver com o projeto

2023-02-23 16:35 UTC, Adan0k commented on PedraPapelTesoura/index.html
> +    <div id="exercise2">
esse id me parece mal, poderia ser mais sugestivo

2023-02-23 16:35 UTC, Adan0k commented on PedraPapelTesoura/index.html
> +    <script src="./changeColor.js"></script>
remove isso
```suggestion
    
```

2023-02-23 16:35 UTC, Adan0k commented on PedraPapelTesoura/rockPaperScissors.js
> +scissors.addEventListener("click", () => {getResult("scissors")});
```suggestion
rock.addEventListener("click", () => getResult("rock"));
paper.addEventListener("click", () => getResult("paper"));
scissors.addEventListener("click", () => getResult("scissors"));
```

2023-02-23 16:35 UTC, Adan0k commented on PedraPapelTesoura/rockPaperScissors.js
> +  cpuInput = Math.floor(Math.random() * 3);
```suggestion
  const cpuInput = Math.floor(Math.random() * 3);
```

2023-02-23 16:35 UTC, Adan0k commented on PedraPapelTesoura/rockPaperScissors.js
> +    cpuInputResult = cpuInputFunction();
```suggestion
   const cpuInputResult = cpuInputFunction();
```

2023-02-23 17:41 UTC, 201flaviosilva requested changes

2023-02-23 17:41 UTC, 201flaviosilva commented on PedraPapelTesoura/Readme.md
> +            }
Se fosses um gajo porreiro podias reduzir este código:

```suggestion
            if (botPlay === ROCK) return DRAW;
            if (botPlay === PAPER) return LOSE;
            if (botPlay === SCISSORS)return WIN;
```

(Mas está ok, é a tua cena , é o que é)

2023-02-23 17:41 UTC, 201flaviosilva commented on PedraPapelTesoura/Readme.md
> +Thanks to the teachers and Mindera for the learning opportunity!
Já gosto mais

2023-02-23 17:41 UTC, 201flaviosilva commented on PedraPapelTesoura/rockPaperScissors.js
> +    }
Acho que sabes o problema daqui

2023-02-23 17:42 UTC, 201flaviosilva commented
Não te esqueças de atualizar o `ReadMe.md`

2023-02-23 18:00 UTC, 201flaviosilva approved these changes
Muito mais legível o código

2023-02-23 18:00 UTC, 201flaviosilva commented on PedraPapelTesoura/script.js
> +};
Nice

2023-02-23 18:08 UTC, Adan0k approved these changes

2023-02-23 18:09 UTC, merged