LogIn SigInUp
mindera-school/MS5-FE-Vanilla-Exercicies pull request #5
Opened 2023-02-22 11:35 UTC by Pedroooliveria

2023-02-22 11:54 UTC, Gabriel-Sous-a requested changes
Todos os nomes deviam ser postos em inglês e devias ter mais atenção aos nomes que das porque deviam ser mais descritivos

2023-02-22 11:54 UTC, Gabriel-Sous-a commented on SigUpLogInPage/LogInSigInUp/index.html
> +    <link rel="stylesheet" href="./style.css" />
O style devia ser posto depois do titulo, queres primeiro que o titulo apareça e só depois dar link ao css. Fizeste bem por o ponto aqui `./style.css`

2023-02-22 11:54 UTC, Gabriel-Sous-a commented on SigUpLogInPage/LogInSigInUp/index.html
> +      <h1 >Mindera School</h1>
```suggestion
      <h1>Mindera School</h1>
```

2023-02-22 11:54 UTC, Gabriel-Sous-a commented on SigUpLogInPage/LogInSigInUp/index.html
> +                <h3 class="h2">Apenas demora alguns segundos</h3>
Bom nome das classes... Não deves por nome de classes ou ids o próprio nome do elemento

2023-02-22 11:54 UTC, Gabriel-Sous-a commented on SigUpLogInPage/LogInSigInUp/index.html
> +              <br />
Se queres dar mais espaço estiliza com o Css

2023-02-22 11:54 UTC, Gabriel-Sous-a commented on SigUpLogInPage/LogInSigInUp/index.html
> +              <div class="color">
Tenta dar nomes mais intuitivos

2023-02-22 11:54 UTC, Gabriel-Sous-a commented on SigUpLogInPage/LogInSigInUp/index.html
> +        We craft softwar witch people we love.
Devias por isto dentro de uma Tag especifica de texto: um `p`, um `a`, um `span`. E aninhas isso dentro do footer

2023-02-22 11:54 UTC, Gabriel-Sous-a commented on SigUpLogInPage/LogInSigInUp/style.css
> +  margin: 0px;
```suggestion
  margin: 0;
```

2023-02-22 11:54 UTC, Gabriel-Sous-a commented on SigUpLogInPage/LogInSigInUp/style.css
> +    margin-top: 1vw;
Margins e paddings usa valores fixos

2023-02-22 11:54 UTC, Gabriel-Sous-a commented on SigUpLogInPage/LogInSigInUp/style.css
> +    box-shadow: 0vw 0vw 90vw 0vw white;
Aqui tambem deves usar valores fixos, troquei só o `vw` para `px` mas tens que olhar para os valores
```suggestion
    box-shadow: 0 0 90px 0 white;
```

2023-02-22 11:54 UTC, Gabriel-Sous-a commented on SigUpLogInPage/LogInSigInUp/style.css
> +    padding-bottom: 1vw;
Põe valores fixos

2023-02-22 12:01 UTC, Adan0k commented on SigUpLogInPage/LogInSigInUp/index.html
> +      <section id="seccao">
Ter um id "secção" numa secção é redundante

2023-02-22 12:01 UTC, Adan0k commented on SigUpLogInPage/LogInSigInUp/index.html
> +        <article id="artigo">
a mesma cena com um artigo

2023-02-22 12:01 UTC, Adan0k commented on SigUpLogInPage/LogInSigInUp/index.html
> +                  class="input"
same

2023-02-22 12:01 UTC, Adan0k commented on SigUpLogInPage/LogInSigInUp/index.html
> +                  class="input"
.

2023-02-22 12:01 UTC, Adan0k commented on SigUpLogInPage/LogInSigInUp/index.html
> +                  class="input"
.

2023-02-22 12:01 UTC, Adan0k commented on SigUpLogInPage/LogInSigInUp/index.html
> +                  class="input"
.

2023-02-22 12:01 UTC, Adan0k commented on SigUpLogInPage/LogInSigInUp/index.html
> +                  class="input"
.

2023-02-22 12:01 UTC, Adan0k commented on SigUpLogInPage/LogInSigInUp/index.html
> +                  class="input"
.

2023-02-22 12:01 UTC, Adan0k commented on SigUpLogInPage/LogInSigInUp/index.html
> +                <h2 class="h2">Criar Conta</h2>
h2 com classe "h2"

2023-02-22 12:01 UTC, Adan0k commented on SigUpLogInPage/LogInSigInUp/index.html
> +                <h3 class="h2">Apenas demora alguns segundos</h3>
podes trocar isso por "subtitle"

2023-02-23 23:02 UTC, 201flaviosilva commented on SigUpLogInPage/LogInSigInUp/index.html
> +        We craft softwar witch people we love.
"softwar" -> "soft" "war" -> uma guerra leve? 😕

2023-02-25 12:50 UTC, LeoHabs commented on SignUpLogInPage/style.css
> +}
Tenho fetish em seletores eficientes 🤤

2023-02-25 12:52 UTC, LeoHabs approved these changes
Aposto que tinha uma ratoeira que não vi ahhaha Anyway adoro a ótima utilização de seletores no css, aspiro a tal

2023-02-27 16:03 UTC, Adan0k approved these changes

2023-02-28 11:48 UTC, Rocha1313 requested changes

2023-02-28 11:48 UTC, Rocha1313 commented on SignUpLogInPage/index.html
> +  <title>SignUp LogIn Page</title>
Acho que ficava melhor assim
```suggestion
  <title>SignUp LogIn</title>
```

2023-02-28 12:27 UTC, 201flaviosilva commented on SignUpLogInPage/index.html
> +  <title>SignUp LogIn Page</title>
Humm, tem o seu sentido, mas como é o nome do projeto também acho que faz sentido ser assim, mas ok, só por cortesia.

2023-02-28 12:28 UTC, 201flaviosilva commented on SignUpLogInPage/index.html
> +  <title>SignUp LogIn Page</title>
(Tanta coisa para comentar, e vai comentar o menos importante, mas ok foi bem apanhado)

2023-02-28 12:35 UTC, Rocha1313 approved these changes

2023-02-28 12:45 UTC, Gabriel-Sous-a approved these changes

2023-02-28 12:45 UTC, Gabriel-Sous-a commented on SignUpLogInPage/index.html
> +  <title>SignUp LogIn</title>
O nome podia ser melhor mas vá aceito
```suggestion
  <title>Sign up and Log in</title>
```

ou 

```suggestion
  <title>SignUp LogIn Exercise</title>
```

2023-02-28 12:45 UTC, Gabriel-Sous-a commented on SignUpLogInPage/style.css
> +}
👌

2023-02-28 13:12 UTC, 201flaviosilva commented on SignUpLogInPage/index.html
> +  <title>SignUp LogIn</title>
Devem pensar que eu tenho a vossa idade para andar a brincar aos PRs 😑

2023-02-28 13:12 UTC, 201flaviosilva commented on SignUpLogInPage/style.css
> +}
👌

2023-02-28 13:12 UTC, merged