add dynamic nav bar
mindera-school/MS5-FE-Vanilla-Exercicies pull request #6
Opened 2023-02-22 11:58 UTC by LeoHabs

# Dynamic Nav Bar
A page with three links that are highlighted when opened

2023-02-23 14:55 UTC, Adan0k requested changes
em geral está bom ,alguns detalhes podem ser melhorados

2023-02-23 14:55 UTC, Adan0k commented on DinamicNavMenu/about.html
> +    <title>Document</title>
O `tittle` pode ser mais descritivo

2023-02-23 14:55 UTC, Adan0k commented on DinamicNavMenu/about.html
> +    <h1 id="h1">About</h1>
um `h1` com o id "h1" é meio redundante
```suggestion
    <h1>About</h1>
```

2023-02-23 14:55 UTC, Adan0k commented on DinamicNavMenu/about.html
> +    <a id="thirdA" href="./contact.html">Contact</a>
os id's podiam ser mais explícitos
```suggestion
    <a id="homeLink" href="./home.html">Home</a>
    <a id="aboutLink" href="./about.html">About</a>
    <a id="contactLink" href="./contact.html">Contact</a>
```

2023-02-23 14:55 UTC, Adan0k commented on DinamicNavMenu/script.js
> +const thirdAnchor = document.getElementById("thirdA");
como os id's foram alterados, tens que alterar aqui também

2023-02-23 14:55 UTC, Adan0k commented on DinamicNavMenu/script.js
> +}
o código não está formatado, era melhor usar os 3 iguais `===`  ,podes usar um switch para substituir esses if's
```suggestion
switch(tittle){
  case "Home":
    firstAnchor.style.backgroundColor = "red";
    break;
  case "About" :
    secondAnchor.style.backgroundColor = "green";
    break;
  case "Contact" :
    thirdAnchor.style.backgroundColor = "pink";
    break;
}
```

2023-02-23 17:06 UTC, Adan0k approved these changes

2023-02-23 17:36 UTC, 201flaviosilva approved these changes
Resolve os conflitos

2023-02-23 17:49 UTC, LeoHabs commented
> Resolve os conflitos

Ja corrigi e apareceu para dar merge mas dps disse q é preciso review

2023-02-23 18:08 UTC, 201flaviosilva commented on README.md
>  | ChangeBGColor | @Adan0k | [Demo](https://mindera-school.github.io/MS5-FE-Vanilla-Exercicies/ChangeBGColor) | [Code](https://github.com/mindera-school/MS5-FE-Vanilla-Exercicies/tree/main/ChangeBGCol
```suggestion

| ChangeBGColor | @Adan0k | [Demo](https://mindera-school.github.io/MS5-FE-Vanilla-Exercicies/ChangeBGColor) | [Code](https://github.com/mindera-school/MS5-FE-Vanilla-Exercicies/tree/main/ChangeBGColor) |
| Dynamic Nav Bar | @LeoHabs | [Demo](https://mindera-school.github.io/MS5-FE-Vanilla-Exercicies/DinamicNavMenu) | [Code](https://github.com/mindera-school/MS5-FE-Vanilla-Exercicies/tree/main/DinamicNavMenu) |
```

2023-02-27 09:58 UTC, Rocha1313 approved these changes

2023-02-27 09:59 UTC, merged