add files tabuada
mindera-school/MS5-FE-Vanilla-Exercicies pull request #7
Opened 2023-02-23 11:19 UTC by LeoHabs

2023-02-23 14:24 UTC, LeoHabs commented on Tabuada/Tabuada/LICENSE.md
> +MIT License
Remover

2023-02-23 14:31 UTC, LeoHabs reviewed
Muda  Manel

2023-02-23 14:31 UTC, LeoHabs commented on Tabuada/Tabuada/LICENSE.md
> +MIT License
Remover

2023-02-23 14:31 UTC, LeoHabs commented on Tabuada/Tabuada/Readme.md
> +Multiplication Table Generator
Colocar syntax markdown

2023-02-23 14:31 UTC, LeoHabs commented on Tabuada/Tabuada/index.html
> +
Formatação do form

2023-02-23 14:31 UTC, LeoHabs commented on Tabuada/Tabuada/index.html
> +        <input type="text" id="multiplierInput">
Não precisa de id
```suggestion
        <input type="text">
```

2023-02-23 14:31 UTC, LeoHabs commented on Tabuada/Tabuada/script.js
> +})
```suggestion
form.addEventListener("submit", e => e.preventDefault());
```

2023-02-23 14:31 UTC, LeoHabs commented on Tabuada/Tabuada/script.js
> +    table.innerHTML = null;
```suggestion
    table.innerHTML = "";
```
Funciona mas deve-se colocar alguma coisa e não mudar para null

2023-02-23 14:31 UTC, LeoHabs commented on Tabuada/Tabuada/script.js
> +    const defTr= document.createElement("tr");
Formatação

2023-02-23 14:31 UTC, LeoHabs commented on Tabuada/Tabuada/style.css
> +}
Formatação

2023-02-23 14:31 UTC, LeoHabs commented on Tabuada/Tabuada/style.css
> +    margin-top: 10%;
Unidades absolutas pls Leo

2023-02-23 14:31 UTC, LeoHabs commented on Tabuada/Tabuada/style.css
> +    border-right: 1px solid;
Colocar `black` por consistência

2023-02-23 17:35 UTC, 201flaviosilva requested changes

2023-02-23 17:35 UTC, 201flaviosilva commented on Tabuada/Readme.md
> +The multiplication table for the input number will be displayed on the screen
```suggestion
2. Press the <strong>"Submit"</strong>> button

The multiplication table for the input number will be displayed on the screen
```

2023-02-23 17:35 UTC, 201flaviosilva commented on Tabuada/index.html
> +    </main>
Formatação
```suggestion
    <main>
      <form id="multiplierForm">
          <input type="text" id="multiplierInput">
          <button type="submit" id="subBtn">Submit</button>
      </form>
      <table id="tabuadaTable">
          <tr>
              <th>Multiplicador</th>
              <th>Multiplicando</th>
              <th>Resultado</th>
          </tr>
      </table>

    </main>
```

2023-02-23 17:35 UTC, 201flaviosilva commented on Tabuada/script.js
> +button.addEventListener("click",()=>{
```suggestion
document.getElementById("subBtn").addEventListener("click",()=>{
```

2023-02-23 17:35 UTC, 201flaviosilva commented on Tabuada/script.js
> +form.addEventListener("submit",(e)=>{
```suggestion
document.getElementById("multiplierForm").addEventListener("submit",(e)=>{
```

2023-02-23 17:35 UTC, 201flaviosilva commented on Tabuada/script.js
> +    table.innerHTML = null;
Chegaste a alterar isto?

2023-02-23 17:35 UTC, 201flaviosilva commented on Tabuada/style.css
> +  background-image: url("");
Não precisas disto aqui

2023-02-23 17:35 UTC, 201flaviosilva commented on Tabuada/Readme.md
> +If you would like to contribute to this project, please fork the repository and submit a pull request with your proposed changes.
Remove isto, isto já está no readme do repo

```suggestion
```

2023-02-23 17:35 UTC, 201flaviosilva commented on Tabuada/Readme.md
> +If you would like to contribute to this project, please fork the repository and submit a pull request with your proposed changes.
Não está, mas deveria

2023-02-27 14:46 UTC, 201flaviosilva approved these changes

2023-02-27 14:46 UTC, 201flaviosilva commented on README.md
> +| Tabuada | @LeoHabs | [Demo](https://mindera-school.github.io/MS5-FE-Vanilla-Exercicies/Tabuada/) | [Code](https://github.com/mindera-school/MS5-FE-Vanilla-Exercicies/tree/main/Tabuada) |
Depois de organizares por ordem alfabética e resolveres os conflitos, remove a linha a mais que o @Rocha1313 adicionou na barnch main

2023-02-27 16:00 UTC, Adan0k requested changes

2023-02-27 16:00 UTC, Adan0k commented on Tabuada/index.html
> +      <form id="multiplierForm">
nome do id é redundante

2023-02-27 16:00 UTC, Adan0k commented on Tabuada/index.html
> +          <input type="text" id="multiplierInput">
aqui também

2023-02-27 16:00 UTC, Adan0k commented on Tabuada/index.html
> +          <button type="submit" id="subBtn">Submit</button>
same

2023-02-27 16:00 UTC, Adan0k commented on Tabuada/index.html
> +      <table id="tabuadaTable">
wow, que novidade! Um id redundante

2023-02-27 16:18 UTC, Adan0k approved these changes

2023-02-27 16:20 UTC, merged