add circular progress bar files
mindera-school/MS5-FE-Vanilla-Exercicies pull request #8
Opened 2023-02-23 11:25 UTC by LeoHabs

2023-02-23 12:15 UTC, Rocha1313 commented on CircularProgressBar/CircularLoad/script.js
> +    progress.innerHTML = slider.value+"%";
You could have done everything directly in percentage instead of converting to deg

2023-02-23 15:01 UTC, Rocha1313 requested changes
Tens que alterar o Readme e tens uma pasta dentro de outra, cuidado com os outros comentarios

2023-02-23 15:01 UTC, Rocha1313 commented on CircularProgressBar/CircularLoad/index.html
> +    <title>Document</title>
Where's the title

2023-02-23 15:01 UTC, Rocha1313 commented on CircularProgressBar/CircularLoad/index.html
> +    <link rel="stylesheet" href="./style.css">
Os estilos devem estar depois do titulo, porque convem carregar o titulo primeiro depois carregar os estilos

2023-02-23 15:01 UTC, Rocha1313 commented on CircularProgressBar/CircularLoad/index.html
> +        </div>
```suggestion
        <div id="circleBorder"></div>
```

2023-02-23 15:01 UTC, Rocha1313 commented on CircularProgressBar/CircularLoad/index.html
> +        </div>
```suggestion
        <div id="circle"></div>
```

2023-02-23 15:01 UTC, Rocha1313 commented on CircularProgressBar/CircularLoad/index.html
> +          </div>
Nao esta formatado

2023-02-23 15:01 UTC, Rocha1313 commented on CircularProgressBar/CircularLoad/script.js
> +slider.addEventListener("input",()=>{
```suggestion
slider.addEventListener("input", () => {
```

2023-02-23 15:01 UTC, Rocha1313 commented on CircularProgressBar/CircularLoad/script.js
> +    let degrees = slider.value * 3.6;
Podias ter usado aqui um `const` em vez de um `let`

2023-02-23 15:01 UTC, Rocha1313 commented on CircularProgressBar/CircularLoad/style.css
> +*{
Nao esta formatado

2023-02-23 15:01 UTC, Rocha1313 commented on CircularProgressBar/CircularLoad/script.js
> +    progress.innerHTML = slider.value+"%";
Nao esta formatado

2023-02-23 16:36 UTC, Rocha1313 requested changes

2023-02-23 16:36 UTC, Rocha1313 commented on CircularProgressBar/script.js
> +    progress.innerHTML = slider.value + "%";
Isto vai dar errado, e esta um pouco redundante 
```suggestion
    border.style.background = "conic-gradient(rgb(6, 214, 160) " + slider.value + "%, black 0%)";
    progress.innerHTML = slider.value + "%";
```

2023-02-23 16:36 UTC, Rocha1313 commented on CircularProgressBar/script.js
> +    progress.innerHTML = slider.value + "%";
Tinhas esquecido de trocar de `deg` para `%`.
E estavas a criar uma variavel praticamente para nada.

2023-02-23 17:00 UTC, Rocha1313 requested changes

2023-02-23 17:00 UTC, Rocha1313 commented on CircularProgressBar/script.js
> +    border.style.background = "conic-gradient(rgb(6, 214, 160) " + percentage + "%, black 0deg)";
Eu usaria `%` nos dois, seguir um padrao
```suggestion
    border.style.background = "conic-gradient(rgb(6, 214, 160) " + percentage + "%, black 0%)";
```

2023-02-23 17:38 UTC, 201flaviosilva approved these changes
Resolve os conflitos

2023-02-23 17:38 UTC, 201flaviosilva commented on CircularProgressBar/index.html
> +          id="slider" />
Para que é que queres uma `class` e um `id` com o mesmo valor?

2023-02-25 12:08 UTC, Rocha1313 approved these changes

2023-02-27 14:44 UTC, 201flaviosilva approved these changes

2023-02-27 14:44 UTC, merged